sudo: required
services:
  - docker
before_install:
  - docker build -t binoymthomas/multi-docker-react-client-dev -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true binoymthomas/multi-docker-react-client-dev npm run test -- --coverage
after_success:
    - docker build -t binoymthomas/multi-docker-react-client:"$TRAVIS_BUILD_NUMBER" ./client
    - docker build -t binoymthomas/multi-docker-react-nginx:"$TRAVIS_BUILD_NUMBER" ./nginx
    - docker build -t binoymthomas/multi-docker-react-server:"$TRAVIS_BUILD_NUMBER" ./server
    - docker build -t binoymthomas/multi-docker-react-worker:"$TRAVIS_BUILD_NUMBER" ./worker
    # Login in to Docker registry
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to Docker Hub
    - docker push binoymthomas/multi-docker-react-client:"$TRAVIS_BUILD_NUMBER"
    - docker push binoymthomas/multi-docker-react-nginx:"$TRAVIS_BUILD_NUMBER"
    - docker push binoymthomas/multi-docker-react-server:"$TRAVIS_BUILD_NUMBER"
    - docker push binoymthomas/multi-docker-react-worker:"$TRAVIS_BUILD_NUMBER"
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker-react"
  env: "MultiDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-024854438350"
  bucket_path: "multi-docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"